# .gitpod.yml - تكوين بيئة Gitpod

tasks:
  - name: Setup Backend & Run Django
    before: |
      # تثبيت متطلبات الباك إند
      cd backend
      pip install -r requirements.txt
      cd ..
      # تثبيت أدوات Flutter (إذا لم يكن مثبتاً تلقائياً)
      # (يمكن إزالة هذا الجزء إذا كان Flutter يعمل دائماً)
      if ! command -v flutter &> /dev/null; then
        echo "Installing Flutter..."
        wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.2-stable.tar.xz -O /tmp/flutter.tar.xz
        tar xf /tmp/flutter.tar.xz -C /workspace
        rm /tmp/flutter.tar.xz
        # لا نحتاج لتحديد PATH هنا لأن .gitpod.yml يتعامل معه غالباً
      fi
    init: |
      # انتظار قاعدة البيانات لتكون جاهزة وتطبيق الهجرات
      echo "Waiting for PostgreSQL..."
      gp await-port 5432 # انتظار منفذ PostgreSQL
      echo "PostgreSQL is ready. Running migrations..."
      cd backend
      python manage.py migrate
      echo "Backend setup complete."
      cd ..
    command: |
      # تشغيل سيرفر Django
      echo "Starting Django development server..."
      cd backend
      python manage.py runserver 0.0.0.0:8000

  - name: Setup Flutter
    init: |
      # جلب حزم Flutter
      echo "Getting Flutter packages..."
      cd mobile_app
      flutter pub get
      echo "Flutter setup complete."
      cd ..
    command: |
      # إبقاء الطرفية مفتوحة لتشغيل أوامر Flutter
      echo "Flutter environment ready. Use 'flutter run' in mobile_app directory."
      cd mobile_app

# تحديد الخدمات التي يجب تشغيلها (قاعدة البيانات)
services:
  - name: postgres
    image: postgres:13 # يمكن استخدام إصدار أحدث إذا أردت
    env:
      POSTGRES_DB: diwan_db_gitpod # يجب أن يطابق الاسم في settings.py
      POSTGRES_USER: gitpod       # يجب أن يطابق المستخدم في settings.py
      # POSTGRES_PASSWORD: '' # كلمة المرور فارغة افتراضياً للمستخدم gitpod

# تحديد المنافذ التي يجب فتحها تلقائياً
ports:
  - port: 8000 # منفذ Django API
    onOpen: open-preview # فتح نافذة لمعاينة الـ API (اختياري)
  - port: 5432 # منفذ PostgreSQL (للاتصال الداخلي)
    onOpen: ignore
  - port: 5900 # VNC (إذا تم تثبيت أدوات UI)
    onOpen: ignore
  - port: 6080 # Web VNC (إذا تم تثبيت أدوات UI)
    onOpen: ignore

# يمكن إضافة إعدادات VS Code هنا (اختياري)
# vscode:
#   extensions:
#     - Dart-Code.flutter
#     - ms-python.python