# .gitpod.yml - Simplified and Corrected

tasks:
  - name: Backend Setup & Run
    before:
      - cd backend
      - pip install -r requirements.txt
    init:
      - gp await-port 5432 # Wait for DB
      - cd backend
      - python manage.py migrate
    command:
      - cd backend
      - python manage.py runserver 0.0.0.0:8000

  - name: Flutter Setup
    before:
      # Install Flutter SDK
      - |
        if ! command -v flutter &> /dev/null; then
          FLUTTER_VERSION="3.22.2" 
          wget -q "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz" -O /tmp/flutter.tar.xz
          tar xf /tmp/flutter.tar.xz -C "$GITPOD_REPO_ROOT" 
          rm /tmp/flutter.tar.xz
          export PATH="$GITPOD_REPO_ROOT/flutter/bin:$PATH"
        fi
    init:
      - cd mobile_app
      # Ensure Flutter PATH is set
      - export PATH="$GITPOD_REPO_ROOT/flutter/bin:$PATH" 
      - flutter pub get
    command:
      - cd mobile_app

services:
  - name: postgres
    image: postgres:13
    env:
      POSTGRES_DB: diwan_db_gitpod
      POSTGRES_USER: gitpod

ports:
  - port: 8000 # Django API
    onOpen: open-preview
  - port: 5432 # PostgreSQL
    onOpen: ignore
  - port: 9000-9099 # Flutter Dev Ports
    onOpen: ignore

vscode:
  extensions:
    - Dart-Code.flutter
    - ms-python.python
