# Generated by Django 5.2 on 2025-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان القصيدة')),
                ('body', models.TextField(help_text='أدخل نص القصيدة كاملاً هنا.', verbose_name='نص القصيدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'قصيدة',
                'verbose_name_plural': 'قصائد',
                'ordering': ['-created_at'],
            },
        ),
    ]
